# Generated by Django 5.2.4 on 2025-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
