# Generated by Django 5.1.11 on 2025-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
